replicaCount: 4

image:
  repository: shubhamdocker413/course-api
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

db:
  # Values for PostgreSQL running inside Kubernetes
  host: postgres-service  # This will be the name of the PostgreSQL service inside your cluster
  port: "5432"
  name: course_db
  user: course_user
  password: course_password

postgresql:
  enabled: true
  image: postgres:14
  storage:
    size: 1Gi

ingress:
  enabled: true
  host: courseapi.local
  path: /
